databases:
  - name: render-test-db
    plan: free
    databaseName: books_db
    user: eugenia

services:
  - type: web
    name: render-test
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: render-test-db
          property: connectionString
